# See: https://www.dartlang.org/tools/pub/pubspec
name: flutter_android
version: 0.0.0
description: >-
  Android Support for Flutter
author: Arto Bendiken <arto@bendiken.net>
homepage: https://github.com/drydart/flutter_android
documentation:
dependencies:
dev_dependencies:
  test: '>=1.3.4 <2.0.0'
dependency_overrides:
environment:
 sdk: '>=2.0.0 <3.0.0'
executables:
