# See: https://dart.dev/tools/pub/pubspec
name: flutter_android
version: 0.8.0
description: >-
  A Flutter plugin for Android platform-specific APIs, to reduce duplication
  of effort by centralizing Android bindings in a single package.
homepage: https://github.com/drydart/flutter_android
repository: https://github.com/drydart/flutter_android
issue_tracker: https://github.com/drydart/flutter_android/issues
documentation:
dependencies:
  flutter:
    sdk: flutter
  typed_data: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
dependency_overrides:
environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"
executables:
flutter:
  plugin:
    platforms:
      android:
        package: com.github.drydart.flutter_android
        pluginClass: FlutterAndroidPlugin
